### ISSUE TITLE
A question on "Federated Learning for Firefox".  

### ISSUE THREAD

**Issue by isaprykin** [florian/federated-learning#2]
I got curious about one point when reading https://florian.github.io/federated-learning-firefox/.

It is something that is described in the paragraph that starts with "From a user perspective, it is not clear if these changes improve the user experience."

Would it have been informative to compute "mean selected rank" for the subset of the treatment group that typed longer sequences such that the "mean characters typed" of the subset is around 4.25?

Thanks.  P.S. I didn't find a better forum to ask this question.

**Comment by florian** [comment]
Yeah, I think that would've been informative, but probably also not sufficient to fully decide since that won't tell you anything about the cases where users found something with fewer characters typed.

I think the way to go about this would probably be to collect metrics
- that correlate rank / characters typed (e.g. like you did)
- that track the rank over time as people enter more characters

I'll close the issue btw, but feel free to ask more questions if you have any!
